(()=>{'use strict';
const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const escapeHTML=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const toast=t=>{let e=$('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)};
let cart=Number(localStorage.getItem('ashkan-cart')||0), wishes=JSON.parse(localStorage.getItem('ashkan-wishes')||'[]');
const sync=()=>{$$('[data-cart-count]').forEach(x=>x.textContent=cart);$$('[data-wish-count]').forEach(x=>x.textContent=wishes.length)};sync();
$$('[data-add]').forEach(b=>b.addEventListener('click',()=>{cart++;localStorage.setItem('ashkan-cart',cart);sync();toast('محصول به سبد خرید اضافه شد ✓')}));
$$('.product').forEach((p,i)=>{const name=$('h3',p)?.textContent?.trim()||`محصول ${i+1}`, img=$('img',p)?.getAttribute('src')||'img/1.jpg', price=$('.price',p)?.textContent||'';const w=$('[data-wish]',p);if(w){if(wishes.some(x=>x.name===name))w.classList.add('active');w.onclick=()=>{const n=wishes.findIndex(x=>x.name===name);if(n>=0){wishes.splice(n,1);w.classList.remove('active');toast('از علاقه‌مندی‌ها حذف شد')}else{wishes.push({name,img,price});w.classList.add('active');toast('به علاقه‌مندی‌ها اضافه شد ♡')}localStorage.setItem('ashkan-wishes',JSON.stringify(wishes));sync()}}const q=$('[data-quick]',p);if(q)q.onclick=()=>openQuick({name,img,price})});
const quick=$('.quick-modal');function openQuick(x){if(!quick)return;$('[data-quick-content]',quick).innerHTML=`<div class="quick-grid"><img src="${escapeHTML(x.img)}" alt=""><div><span class="eyebrow blue">مشاهده سریع</span><h2>${escapeHTML(x.name)}</h2><p>ضمانت اصالت کالا، ارسال سریع و امکان بازگشت تا ۷ روز.</p><div class="price">${escapeHTML(x.price)}</div><div class="quick-actions"><a class="btn btn-soft" href="single-product.html">جزئیات محصول</a><button class="btn btn-primary" data-modal-add>افزودن به سبد</button></div></div></div>`;quick.classList.add('open');quick.setAttribute('aria-hidden','false');$('[data-modal-add]',quick).onclick=()=>{cart++;localStorage.setItem('ashkan-cart',cart);sync();toast('محصول به سبد اضافه شد ✓')}}
$('.quick-close')?.addEventListener('click',()=>quick.classList.remove('open'));quick?.addEventListener('click',e=>{if(e.target===quick)quick.classList.remove('open')});
const themeBtn=$('[data-theme]');const applyTheme=t=>{document.documentElement.dataset.theme=t;localStorage.setItem('ashkan-theme',t);if(themeBtn)themeBtn.textContent=t==='dark'?'☀️':'🌙'};applyTheme(localStorage.getItem('ashkan-theme')|| (matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'));themeBtn?.addEventListener('click',()=>applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark'));
const palette=$('.command-palette'),commandInput=$('[data-command-input]');const toggleCommand=(open=true)=>{if(!palette)return;palette.classList.toggle('open',open);palette.setAttribute('aria-hidden',String(!open));if(open)setTimeout(()=>commandInput?.focus(),30)};$('[data-command]')?.addEventListener('click',()=>toggleCommand(true));palette?.addEventListener('click',e=>{if(e.target===palette)toggleCommand(false)});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();toggleCommand(true)}if(e.key==='Escape'){toggleCommand(false);quick?.classList.remove('open')}});commandInput?.addEventListener('input',()=>{const v=commandInput.value.trim();$$('.command-list a').forEach(a=>a.hidden=!!v&&!a.textContent.includes(v))});
const chat=$('.chat'),chatBtn=$('.chat-btn');if(chatBtn&&chat){chatBtn.onclick=()=>chat.classList.toggle('open');$('.chat-close')?.addEventListener('click',()=>chat.classList.remove('open'));$('.chat-form')?.addEventListener('submit',e=>{e.preventDefault();const input=$('.chat-form input'),v=input.value.trim();if(!v)return;const user=document.createElement('div');user.className='msg user';user.textContent=v;$('.chat-body').append(user);input.value='';setTimeout(()=>{let r='می‌توانم درباره انتخاب محصول، مقایسه، بودجه، ارسال و خرید راهنمایی‌تان کنم.';if(/لپ.?تاپ|کامپیوتر/.test(v))r='بودجه و نوع استفاده‌تان مثل برنامه‌نویسی، طراحی یا بازی را بگویید تا گزینه مناسب‌تری پیشنهاد کنم.';else if(/گوشی|موبایل/.test(v))r='بودجه و اولویت شما مثل دوربین، باتری، نمایشگر یا بازی چیست؟';else if(/ارسال|تحویل/.test(v))r='ارسال قابل پیگیری است؛ برای نسخه نمایشی می‌توانید صفحه پیگیری سفارش را امتحان کنید.';else if(/مقایسه/.test(v))r='از صفحه مقایسه می‌توانید مشخصات چند محصول را کنار هم ببینید.';const bot=document.createElement('div');bot.className='msg bot';bot.textContent=r;$('.chat-body').append(bot);$('.chat-body').scrollTop=$('.chat-body').scrollHeight},350)})}
const q=$('[data-search]');q?.addEventListener('input',()=>{const term=q.value.trim();$$('.product').forEach(p=>p.style.display=!term||p.innerText.includes(term)?'block':'none')});
const timer=$('[data-timer]');if(timer){let s=5*3600+42*60+17;const tick=()=>{s=Math.max(0,s-1);const h=String(Math.floor(s/3600)).padStart(2,'0'),m=String(Math.floor(s%3600/60)).padStart(2,'0'),sec=String(s%60).padStart(2,'0');timer.innerHTML=`<div><b>${h}</b><small>ساعت</small></div><div><b>${m}</b><small>دقیقه</small></div><div><b>${sec}</b><small>ثانیه</small></div>`};tick();setInterval(tick,1000)}
$$('form[data-demo]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();toast('اطلاعات با موفقیت ثبت شد (نسخه نمایشی)')}));
const back=$('.back-top');addEventListener('scroll',()=>back?.classList.toggle('show',scrollY>450),{passive:true});back?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));
if(document.body.dataset.page==='wishlist'){const box=$('[data-wishlist]');const render=()=>{wishes=JSON.parse(localStorage.getItem('ashkan-wishes')||'[]');box.innerHTML=wishes.length?wishes.map((x,i)=>`<article class="wish-row"><img src="${escapeHTML(x.img)}" alt=""><div><h3>${escapeHTML(x.name)}</h3><div class="price">${escapeHTML(x.price)}</div></div><button class="btn btn-soft" data-remove-wish="${i}">حذف</button></article>`).join(''):'<div class="empty-state"><b>هنوز محصولی ذخیره نکرده‌اید</b><p>محصولات موردعلاقه را با آیکن ♡ ذخیره کنید.</p><a class="btn btn-primary" href="archive.html">مشاهده محصولات</a></div>';$$('[data-remove-wish]').forEach(b=>b.onclick=()=>{wishes.splice(+b.dataset.removeWish,1);localStorage.setItem('ashkan-wishes',JSON.stringify(wishes));sync();render()})};render()}
if('serviceWorker' in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
/* Advanced commerce modules */
(()=>{'use strict';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
const fa=n=>Number(n).toLocaleString('fa-IR');
const safeParse=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const notify=(m)=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.append(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
// Smart search suggestions
const inventory=[{n:'لپ‌تاپ NovaBook Pro 14',i:'img/1.jpg',p:'۴۸,۹۰۰,۰۰۰ تومان'},{n:'گوشی Nova X Pro 256GB',i:'img/2.jpg',p:'۳۶,۵۰۰,۰۰۰ تومان'},{n:'مانیتور UltraView 27 QHD',i:'img/img.jpg',p:'۱۸,۷۵۰,۰۰۰ تومان'},{n:'هدفون AirBeat ANC',i:'img/2.jpg',p:'۶,۴۹۰,۰۰۰ تومان'}];
$$('[data-search]').forEach(input=>{const box=input.parentElement.querySelector('[data-suggestions]');if(!box)return;input.addEventListener('input',()=>{const q=input.value.trim();if(!q){box.classList.remove('open');return}const hits=inventory.filter(x=>x.n.includes(q)).slice(0,4);box.innerHTML=hits.map(x=>`<a class="suggest-item" href="single-product.html"><img src="${x.i}" alt=""><span><b>${x.n}</b><small>${x.p}</small></span></a>`).join('')+`<a class="suggest-all" href="archive.html?q=${encodeURIComponent(q)}">مشاهده همه نتایج برای «${q}»</a>`;box.classList.add('open')});input.addEventListener('keydown',e=>{if(e.key==='Enter'&&input.value.trim())location.href='archive.html?q='+encodeURIComponent(input.value.trim())})});
// Notifications
const drawer=$('.notify-drawer');$$('[data-notifications]').forEach(b=>b.onclick=()=>drawer?.classList.add('open'));$('[data-close-notify]')?.addEventListener('click',()=>drawer.classList.remove('open'));$('[data-read-all]')?.addEventListener('click',()=>{$$('[data-notify-count]').forEach(x=>x.textContent='0');notify('همه اعلان‌ها خوانده شدند')});
// Compare persistence
let compare=safeParse('ashkan-compare');const addCompare=(name,img='img/1.jpg',price='')=>{if(compare.some(x=>x.name===name))return notify('این محصول قبلاً در مقایسه است');if(compare.length>=4)return notify('حداکثر ۴ محصول قابل مقایسه است');compare.push({name,img,price,cpu:'Core Ultra 7',ram:'16GB',storage:'1TB SSD',display:'14 OLED'});localStorage.setItem('ashkan-compare',JSON.stringify(compare));notify('به مقایسه اضافه شد ⚖')};$$('[data-compare]').forEach(b=>b.onclick=()=>{const p=b.closest('.product')||b.closest('.advanced-detail');addCompare(p?.querySelector('h3,h1')?.textContent.trim()||'NovaBook Pro 14',p?.querySelector('img')?.src||'img/1.jpg',p?.querySelector('.price,h2')?.textContent||'')});
const renderCompare=()=>{const box=$('[data-compare-table]');if(!box)return;compare=safeParse('ashkan-compare');if(!compare.length){box.innerHTML='<div class="empty-state"><b>هنوز محصولی برای مقایسه ندارید</b><p>از فروشگاه محصول اضافه کنید یا از انتخاب‌گر بالا استفاده کنید.</p></div>';return}const rows=[['قیمت','price'],['پردازنده','cpu'],['رم','ram'],['حافظه','storage'],['نمایشگر','display']];box.innerHTML=`<div class="compare-grid" style="--compare-count:${compare.length}"><div class="compare-cell head">محصول</div>${compare.map((x,i)=>`<div class="compare-cell compare-product"><button data-remove-compare="${i}">✕</button><img src="${x.img}"><b>${x.name}</b></div>`).join('')}${rows.map(r=>`<div class="compare-cell head">${r[0]}</div>${compare.map(x=>`<div class="compare-cell">${x[r[1]]||'—'}</div>`).join('')}`).join('')}</div>`;$$('[data-remove-compare]',box).forEach(b=>b.onclick=()=>{compare.splice(+b.dataset.removeCompare,1);localStorage.setItem('ashkan-compare',JSON.stringify(compare));renderCompare()})};renderCompare();$('[data-compare-add]')?.addEventListener('click',()=>{const s=$('[data-compare-picker]');if(!s.value)return;const [name,img,price,cpu,ram,storage,display]=s.value.split('|');if(compare.length>=4)return notify('حداکثر ۴ محصول');compare.push({name,img,price,cpu,ram,storage,display});localStorage.setItem('ashkan-compare',JSON.stringify(compare));renderCompare()});$('[data-clear-compare]')?.addEventListener('click',()=>{compare=[];localStorage.setItem('ashkan-compare','[]');renderCompare()});
// Advanced catalog filters, sort and view
const catalog=$('[data-catalog]');if(catalog){const items=$$('.product',catalog);const apply=()=>{const text=$('[data-filter-text]')?.value.trim()||'',cats=$$('[data-cat]:checked').map(x=>x.dataset.cat),brands=$$('[data-brand]:checked').map(x=>x.dataset.brand),max=+$('[data-price-range]')?.value||9e9,stock=$('[data-in-stock]')?.checked;let visible=0;items.forEach(x=>{const ok=(!text||x.innerText.includes(text))&&(!cats.length||cats.includes(x.dataset.category))&&(!brands.length||brands.includes(x.dataset.brand))&&(+x.dataset.price<=max)&&(!stock||x.dataset.stock==='yes');x.hidden=!ok;if(ok)visible++});$('[data-result-count]').textContent=fa(visible);$('[data-empty-filter]').hidden=visible>0;const chips=[];cats.forEach(x=>chips.push(x));brands.forEach(x=>chips.push(x));if(stock)chips.push('فقط موجود');$('[data-active-filters]').innerHTML=chips.map(x=>`<span class="filter-chip">${x}</span>`).join('')};$$('[data-cat],[data-brand],[data-in-stock],[data-filter-text]').forEach(x=>x.addEventListener('input',apply));$('[data-price-range]')?.addEventListener('input',e=>{$('[data-price-label]').textContent=fa(e.target.value);apply()});$$('[data-filter-reset]').forEach(b=>b.onclick=()=>{$$('[data-cat],[data-brand],[data-in-stock]').forEach(x=>x.checked=false);if($('[data-filter-text]'))$('[data-filter-text]').value='';if($('[data-price-range]'))$('[data-price-range]').value=85000000;apply()});$('[data-sort]')?.addEventListener('change',e=>{const arr=[...items];if(e.target.value==='cheap')arr.sort((a,b)=>+a.dataset.price-+b.dataset.price);if(e.target.value==='expensive')arr.sort((a,b)=>+b.dataset.price-+a.dataset.price);arr.forEach(x=>catalog.append(x))});$$('[data-view]').forEach(b=>b.onclick=()=>{$$('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');catalog.classList.toggle('list-view',b.dataset.view==='list')});const q=new URLSearchParams(location.search).get('q');if(q&&$('[data-filter-text]')){$('[data-filter-text]').value=q;apply()}}
// Coupon
$('[data-apply-coupon]')?.addEventListener('click',()=>{const code=$('[data-coupon]').value.trim().toUpperCase(),msg=$('[data-coupon-msg]');if(code==='ASHKAN10'){$('.discount-line').hidden=false;$('[data-final-price]').textContent='۴۹,۸۵۱,۰۰۰ تومان';msg.textContent='✓ تخفیف ۱۰٪ با موفقیت اعمال شد';msg.style.color='#059669';localStorage.setItem('ashkan-coupon',code);notify('کد تخفیف اعمال شد')}else{msg.textContent='کد واردشده معتبر نیست';msg.style.color='#dc2626'}});
// Product gallery zoom, quantity, tabs, reviews
$$('[data-thumb]').forEach(b=>b.onclick=()=>{$$('[data-thumb]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('[data-main-image]').src=b.dataset.thumb});const zoom=$('[data-zoom-wrap]');zoom?.addEventListener('mousemove',e=>{const r=zoom.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100,img=$('[data-main-image]');img.style.transformOrigin=`${x}% ${y}%`;img.style.transform='scale(1.8)'});zoom?.addEventListener('mouseleave',()=>{$('[data-main-image]').style.transform='scale(1)'});$('[data-qty-plus]')?.addEventListener('click',()=>{const q=$('[data-qty]');q.value=Math.min(10,+q.value+1)});$('[data-qty-minus]')?.addEventListener('click',()=>{const q=$('[data-qty]');q.value=Math.max(1,+q.value-1)});$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));$$('[data-panel]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`[data-panel="${b.dataset.tab}"]`).classList.add('active')});let stars=5;$$('[data-star]').forEach(b=>b.onclick=()=>{stars=+b.dataset.star;$$('[data-star]').forEach(x=>x.textContent=+x.dataset.star<=stars?'★':'☆')});$('[data-review-form]')?.addEventListener('submit',e=>{e.preventDefault();const ins=$$('input,textarea',e.currentTarget),article=document.createElement('article');article.innerHTML=`<b>${ins[0].value.replace(/[<>]/g,'')}</b><span>${'★'.repeat(stars)}${'☆'.repeat(5-stars)}</span><p>${ins[1].value.replace(/[<>]/g,'')}</p>`;$('[data-reviews]').prepend(article);e.currentTarget.reset();notify('دیدگاه شما ثبت شد (نسخه نمایشی)')});
// Recently viewed
if(location.pathname.endsWith('single-product.html')){let r=safeParse('ashkan-recent');r=r.filter(x=>x.name!=='NovaBook Pro 14');r.unshift({name:'NovaBook Pro 14',img:'img/1.jpg',price:'۴۸,۹۰۰,۰۰۰ تومان'});localStorage.setItem('ashkan-recent',JSON.stringify(r.slice(0,6)))}$$('[data-recently]').forEach(box=>{const r=safeParse('ashkan-recent',[{name:'NovaBook Pro 14',img:'img/1.jpg',price:'۴۸,۹۰۰,۰۰۰ تومان'},{name:'Nova X Pro',img:'img/2.jpg',price:'۳۶,۵۰۰,۰۰۰ تومان'}]);box.innerHTML=r.map(x=>`<article class="product"><a href="single-product.html"><div class="product-img"><img src="${x.img}" alt="${x.name}"></div><h3>${x.name}</h3></a><div class="rating">★★★★★</div><div class="price">${x.price}</div></article>`).join('')});
// Checkout
let step=1;const renderStep=()=>{$$('[data-step]').forEach(x=>x.classList.toggle('active',+x.dataset.step===step));$$('[data-step-dot]').forEach(x=>x.classList.toggle('active',+x.dataset.stepDot<=step));$('[data-checkout-prev]')?.toggleAttribute('hidden',step===1);if($('[data-checkout-next]'))$('[data-checkout-next]').textContent=step===4?'ثبت نهایی سفارش':'ادامه';if(step===4){const n=$('[data-field="name"]')?.value||'—',a=$('[data-field="address"]')?.value||'—';$('[data-final-address]').innerHTML=`<b>${n}</b><p>${a}</p>`}};$('[data-checkout-next]')?.addEventListener('click',()=>{if(step===1){const req=$$('[data-step="1"] [required]');if(req.some(x=>!x.value.trim()))return notify('لطفاً اطلاعات ارسال را کامل کنید')}if(step<4){step++;renderStep()}else{const order={id:'AE-'+Date.now().toString().slice(-8),date:new Date().toISOString(),total:'۴۸,۹۰۰,۰۰۰ تومان'};const orders=safeParse('ashkan-orders');orders.unshift(order);localStorage.setItem('ashkan-orders',JSON.stringify(orders));notify('سفارش با موفقیت ثبت شد ✓');setTimeout(()=>location.href='orders.html',900)}});$('[data-checkout-prev]')?.addEventListener('click',()=>{if(step>1){step--;renderStep()}});
// Profile demo persistence
$('[data-profile-form]')?.addEventListener('submit',e=>{e.preventDefault();localStorage.setItem('ashkan-profile',JSON.stringify($$('input',e.currentTarget).map(x=>x.value)));notify('تغییرات پروفایل ذخیره شد')});
// Skeleton simulation for catalog first load
if(catalog){catalog.classList.add('loading-products');setTimeout(()=>catalog.classList.remove('loading-products'),350)}
})();
